### ISSUE TITLE
JSON insufficient for the openapi document.

### ISSUE THREAD

**Issue by dcroshere** [open-ag-tech/api-spec#13]
During the June 28th TSC meeting, we held an informal vote and agreed on JSON.

I was tasked with creating a base document from which we could create examples. After noting that all of the existing openAPI examples are in YAML, I checked out why:

These documents often use a "$ref: '#/path/to/object'" method of relating objects together. It is a feature unique to YAML. I think we'll need to do YAML for this document, although we can still use JSON for actual calls.

**Comment by jtorreggiani** [comment]
@dcroshere, are you sure that is unique to YAML? Unless I am reading the Open API document incorrectly, it looks like they provide an example of using `$ref` in JSON. https://swagger.io/docs/specification/using-ref

**Comment by dcroshere** [comment]
You are correct, this is my mistake.
